import React from "react";
import "./globals.css";
import PageLayout from "@/components/PageLayout";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

// RootLayout component
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
